services:
  app:
    build:
      context: .
    image: docker-spring-boot-postgres:latest
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compt_rendu
      - SPRING_DATASOURCE_USERNAME=breukh
      - SPRING_DATASOURCE_PASSWORD=breukh
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8080
    restart: unless-stopped
    volumes:
      - ./uploads:/uploads  #

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=breukh
      - POSTGRES_PASSWORD=breukh
      - POSTGRES_DB=compt_rendu
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
